[package]
name = "teiji-notify"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_yml = "0.0.12"
