[package]
name = "teiji-notify"
version = "0.0.1"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.47", features = ["derive"] }
notify-rust = "4.11.7"
serde = { version = "1.0.219", features = ["derive"] }
serde_yml = "0.0.12"
